[build-system]
requires = ["setuptools>=61.0", "streamlit==1.11.1"]
build-backend = "setuptools.build_meta"

[project]
name = "streamlit_extras"
version = "0.0.9"
authors = [
  { name="Arnaud Miribel", email="arnaudmiribel@gmail.com" },
]
description = "A library to discover, try, install and share Streamlit extras"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
]
keywords = [
    "python",
    "streamlit",
    "ui",
    "data",
]
dependencies = [
  "htbuilder",
  "st-annotated-text",
  "streamlit-embedcode",
  "streamlit-keyup"
]

[project.urls]
"Homepage" = "https://github.com/arnaudmiribel/streamlit-extras"
"Bug Tracker" = "https://github.com/arnaudmiribel/streamlit-extras/issues"

[tool.isort]
profile = "black"
line_length = 88
skip = ["./.venv", "./direnv", ".env"]

[tool.black]
exclude = '''
(
  /(
      \.vscode
    | \.git
    | \.pytest_cache
    | \.mypy_cache
    | \.venv
    | \.env
    | \.direnv
  )/
)
'''
include = '\.pyi?$'
line-length = 88

[tool.mypy]
files = [
  "**/*.py",
]
follow_imports = "silent"
ignore_missing_imports = true
scripts_are_modules = true
python_version = 3.9