name: "💬 Something else..."
description: Create a ticket to share an idea of a new extra.
title: ""
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: Short and explicit description of your issue/idea
    validations:
      required: true
